# Generated by Django 4.0.4 on 2022-05-18 00:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('banner', models.ImageField(blank=True, db_column='BANNER', upload_to='')),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=250)),
                ('course_type', models.CharField(db_column='COURSE_TYPE', max_length=50)),
                ('course_objective', models.CharField(db_column='COURSE_OBJETIVE', max_length=250)),
                ('curriculum', models.ImageField(blank=True, db_column='CURRICULUM', upload_to='')),
                ('completion_profile', models.CharField(db_column='COMPLETION_PROFILE', max_length=100)),
                ('duration_time', models.CharField(db_column='DURATION_TIME', max_length=5)),
                ('occupation_area', models.CharField(db_column='OCCUPATION_AREA', max_length=50)),
                ('modality', models.CharField(db_column='MODALITY', max_length=50)),
                ('value', models.FloatField(db_column='VALUE')),
                ('is_activate', models.BooleanField(db_column='IS_ACTIVE')),
                ('enrollment', models.BooleanField(db_column='ENROLLMENT')),
                ('mec_score', models.CharField(choices=[('1', 'MEC_SCORE_1'), ('2', 'MEC_SCORE_2'), ('3', 'MEC_SCORE_3'), ('4', 'MEC_SCORE_4'), ('5', 'MEC_SCORE_5')], db_column='MEC_SCORE', max_length=2)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'COURSE',
                'ordering': ['name'],
            },
        ),
    ]
