# Generated by Django 4.0.4 on 2022-05-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
    ]
