# Generated by Django 4.0.4 on 2022-06-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_coursemodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='value',
        ),
    ]
