# Generated by Django 4.0.4 on 2022-05-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_program', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school_programmodel',
            options={'verbose_name': 'school_program', 'verbose_name_plural': 'school_programs'},
        ),
    ]
