# Generated by Django 4.0.5 on 2022-07-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('school_program', '0002_alter_school_programmodel_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_programmodel',
            name='subjects',
            field=models.ManyToManyField(blank=True, db_column='SUBJECTS', related_name='school_programs', to='subject.subjectmodel'),
        ),
    ]
