# Generated by Django 4.0.4 on 2022-06-20 02:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentModel',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title_enrollment', models.CharField(blank=True, db_column='TITLE_ENROLLMENT', max_length=50, unique=True)),
                ('date_initial', models.DateField(db_column='DATE_INITIAL')),
                ('date_final', models.DateField(db_column='DATE_FINAL')),
                ('courses', models.ForeignKey(db_column='COURSES', on_delete=django.db.models.deletion.CASCADE, to='course.coursemodel')),
                ('universities', models.ForeignKey(db_column='UNIVERSITIES', on_delete=django.db.models.deletion.CASCADE, to='university.universitymodel')),
            ],
            options={
                'verbose_name': 'enrollment',
                'verbose_name_plural': 'enrollments',
                'db_table': 'ENROLLMENT',
            },
        ),
    ]
