# Generated by Django 4.0.5 on 2022-06-24 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_coursemodel_description_and_more'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentmodel',
            name='courses',
            field=models.ForeignKey(db_column='COURSES', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='course.coursemodel'),
        ),
    ]
