# Generated by Django 4.0.5 on 2022-07-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentmodel',
            name='courses',
            field=models.ForeignKey(db_column='COURSES', on_delete=django.db.models.deletion.DO_NOTHING, related_name='enrollments', to='course.coursemodel'),
        ),
    ]
