# Generated by Django 4.0.4 on 2022-05-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollmentmodel',
            options={'verbose_name': 'enrollment', 'verbose_name_plural': 'enrollments'},
        ),
    ]
