# Generated by Django 4.0.4 on 2022-06-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_enrollmentmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentmodel',
            name='title_enrollment',
            field=models.CharField(blank=True, db_column='TITLE_ENROLLMENT', max_length=50),
        ),
    ]
