# Generated by Django 4.0.4 on 2022-06-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_alter_enrollmentmodel_title_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentmodel',
            name='title_enrollment',
            field=models.CharField(blank=True, db_column='TITLE_ENROLLMENT', max_length=50, unique=True),
        ),
    ]
