# Generated by Django 4.0.4 on 2022-05-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='description',
            field=models.TextField(blank=True, db_column='DESCRIPTION'),
        ),
    ]
