# Generated by Django 4.0.4 on 2022-05-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_alter_subjectmodel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmodel',
            options={'verbose_name': 'subject', 'verbose_name_plural': 'subjects'},
        ),
    ]
