# Generated by Django 4.0.4 on 2022-06-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_alter_subjectmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='name',
            field=models.CharField(db_column='NAME', max_length=50, unique=True),
        ),
    ]
