# Generated by Django 4.0.4 on 2022-06-20 02:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityModel',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('telephone', models.CharField(blank=True, db_column='TELEPHONE', max_length=14)),
                ('phone_number', models.CharField(db_column='PHONE_NUMBER', max_length=15)),
                ('attendance', models.TextField(db_column='ATTENDANCE')),
                ('email', models.EmailField(db_column='EMAIL', max_length=254)),
                ('street', models.CharField(db_column='STREET', max_length=100)),
                ('neighborhood', models.CharField(db_column='NEIGHBORHOOD', max_length=100)),
                ('city', models.CharField(db_column='CITY', max_length=50)),
                ('state', models.CharField(choices=[('SC', 'Santa Catarina')], db_column='STATE', max_length=2)),
                ('zip_code', models.CharField(db_column='ZIP_CODE', max_length=9)),
                ('house_number', models.CharField(db_column='HOUSE_NUMBER', max_length=5)),
                ('university_image_local', models.ImageField(blank=True, db_column='UNIVERSITY_IMAGE_LOCAL', upload_to='')),
                ('is_activate', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('courses', models.ManyToManyField(blank=True, to='course.coursemodel')),
            ],
            options={
                'verbose_name': 'university',
                'verbose_name_plural': 'universities',
                'db_table': 'UNIVERSITY',
            },
        ),
    ]
