# Generated by Django 4.0.4 on 2022-05-04 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityModel',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('telephone', models.CharField(db_column='TELEPHONE', max_length=14)),
                ('phone_number', models.CharField(db_column='PHONE_NUMBER', max_length=15)),
                ('email', models.EmailField(db_column='EMAIL', max_length=254)),
                ('street', models.CharField(db_column='STREET', max_length=100)),
                ('neighborhood', models.CharField(db_column='NEIGHBOURHOOD', max_length=100)),
                ('city', models.CharField(db_column='CITY', max_length=50)),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapa'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceara'), ('ES', 'Espirito Santo'), ('GO', 'Goias'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Para'), ('PB', 'Paraiba'), ('PR', 'Parana'), ('PE', 'Pernambuco'), ('PI', 'Piaui'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande Do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('DF', 'Distrito Federal')], db_column='STATE', max_length=2)),
                ('zip_code', models.CharField(db_column='ZIP_CODE', max_length=8)),
                ('house_number', models.CharField(db_column='HOUSE_NUMBER', max_length=5)),
            ],
            options={
                'verbose_name': 'university',
                'verbose_name_plural': 'universities',
                'db_table': 'UNIVERSITY',
            },
        ),
    ]
