# Generated by Django 4.0.4 on 2022-05-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universitymodel',
            options={'verbose_name': 'university', 'verbose_name_plural': 'universities'},
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='state',
            field=models.CharField(choices=[('SC', 'Santa Catarina'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapa'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceara'), ('ES', 'Espirito Santo'), ('GO', 'Goias'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Para'), ('PB', 'Paraiba'), ('PR', 'Parana'), ('PE', 'Pernambuco'), ('PI', 'Piaui'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande Do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('DF', 'Distrito Federal')], db_column='STATE', max_length=2),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='telephone',
            field=models.CharField(db_column='TELEPHONE', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='zip_code',
            field=models.CharField(db_column='ZIP_CODE', max_length=9),
        ),
    ]
