# Generated by Django 4.0.4 on 2022-05-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universitymodel',
            options={'ordering': ['name'], 'verbose_name': 'university', 'verbose_name_plural': 'universities'},
        ),
        migrations.AddField(
            model_name='universitymodel',
            name='courses',
            field=models.ManyToManyField(to='course.coursemodel'),
        ),
    ]
