# Generated by Django 4.0.5 on 2022-06-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitymodel',
            name='phone_number',
            field=models.CharField(blank=True, db_column='PHONE_NUMBER', max_length=15),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='telephone',
            field=models.CharField(db_column='TELEPHONE', max_length=14),
        ),
    ]
