# Generated by Django 4.0.5 on 2022-07-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitymodel',
            name='courses',
            field=models.ManyToManyField(blank=True, to='course.coursemodel'),
        ),
    ]
