# Generated by Django 4.0.4 on 2022-06-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_universitymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitymodel',
            name='state',
            field=models.CharField(choices=[('SC', 'Santa Catarina')], db_column='STATE', max_length=2),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='telephone',
            field=models.CharField(blank=True, db_column='TELEPHONE', default='', max_length=14),
            preserve_default=False,
        ),
    ]
