# Generated by Django 4.0.4 on 2022-06-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_universitymodel_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitymodel',
            name='is_activate',
            field=models.BooleanField(db_column='IS_ACTIVE', default=True),
        ),
    ]
