# Generated by Django 4.0.4 on 2022-06-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_coursemodel_value'),
        ('university', '0004_universitymodel_is_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitymodel',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='universities', to='course.coursemodel'),
        ),
    ]
