# Generated by Django 4.0.4 on 2022-06-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_coursemodel_value'),
        ('university', '0005_alter_universitymodel_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitymodel',
            name='courses',
            field=models.ManyToManyField(blank=True, to='course.coursemodel'),
        ),
    ]
